### PR TITLE
Version 5

### LINKED ISSUE #20: .route convert times
convert departure and arrival times from "16:22" into Date.

convert duration from "HH:mm" to min

### LINKED ISSUE #21: .pins types
add pin types, add request for multiple types.

### LINKED ISSUE #22: .pins stop: parse connection type
add name, icon for connection type

### LINKED ISSUE #34: Migrate to WebAPI
Since EFA is going to be shut down at some point in the rather near future, it seems like a good idea to use the chance to migrate to use the WebAPI instead and also replace the widgets endpoint while at it.

Big upside is a whole bunch of new data being supplied by the WebAPI.

### LINKED ISSUE #38: .route is not working
> StatusCodeError: 404 - The specified URL cannot be found.

this method uses the XML request and is failing for both vvo-online and faplino.

### LINKED ISSUE #40: dvb.find() and dvb.monitor() returning undefined for some stop searches
Something just changed here last night. Please have a look at the following:

```
> dvb.find("Körnerplatz", function(err, data) { console.log(data); });
> undefined
```

But the following works:

```
> dvb.find("Körnerplat", function(err, data) { console.log(data); });
> [ { stop: 'Körnerplatz',
    id: '33000832',
    city: 'Dresden',
    coords: [ 51.05411984235784, 13.814664768428816 ] },
  { stop: 'Körnerplatz',
    id: '36080103',
    city: 'Döbeln',
    coords: [ 51.1189877898748, 13.118164070373634 ] },
  { stop: 'Körnerplatz-Schule',
    id: '36080155',
    city: 'Döbeln',
    coords: [ 51.117933714936974, 13.118409987591615 ] } ]
```

Please note that I simply removed the `z` at the end of "Körnerplatz" to actually find a match.  Also note please that the following strange search requests also find a match:

using `Koernerplatz`:
```
> dvb.find("Koernerplatz", function(err, data) { console.log(data); });
> [ { stop: 'Körnerplatz',
    id: '33000832',
    city: 'Dresden',
    coords: [ 51.05411984235784, 13.814664768428816 ] },
  { stop: 'Körnerplatz',
    id: '36080103',
    city: 'Döbeln',
    coords: [ 51.1189877898748, 13.118164070373634 ] },
  { stop: 'Körnerplatz-Schule',
    id: '36080155',
    city: 'Döbeln',
    coords: [ 51.117933714936974, 13.118409987591615 ] } ]
```

using 'Kornerplatz' (no umlaut:
```
> dvb.find("Kornerplatz", function(err, data) { console.log(data); });
> [ { stop: 'Körnerplatz',
    id: '33000832',
    city: 'Dresden',
    coords: [ 51.05411984235784, 13.814664768428816 ] },
  { stop: 'Körnerplatz',
    id: '36080103',
    city: 'Döbeln',
    coords: [ 51.1189877898748, 13.118164070373634 ] },
  { stop: 'Körnerplatz-Schule',
    id: '36080155',
    city: 'Döbeln',
    coords: [ 51.117933714936974, 13.118409987591615 ] },
  { stop: 'Tzschirnerplatz',
    id: '36060419',
    city: 'Mittweida',
    coords: [ 50.986900674158946, 12.976825926925255 ] } ]
```

Please that this even matches stops in Mittweida where just "platz" is a real match in the search string?!?!

So do you guys know if the VVO changed something last night regarding the search syntax? I find it quite awkward how searches work now and find it especially strange that a direct match for `Körnerplatz` doesn't work at all anymore?!?!

### LINKED ISSUE #41: Bubble up API errors
The WebAPI outputs errors on malformed requests. It would probably make sense to bubble these up as well so that a user of dvbjs doesn't just get an `undefined` to work with.

Somewhat related: #40

Example:

```js
{
  "ResponseStatus": {
    "ErrorCode": "ArgumentException",
    "Message": "Die angegebene DateTime stellt eine ungültige Zeit dar. Wenn die Uhr beispielsweise vorgestellt wird, ist jede Uhrzeit innerhalb des übersprungenen Zeitraums ungültig.\r\nParametername: dateTime"
  }
}

{
  "Status": {
    "Code": "ValidationError",
    "Message": "time has to be a valid time in the future"
  }
}

{
  "Status": {
    "Code": "ValidationError",
    "Message": "stopid has to be not null and must be a number"
  }
}
```

### PR DESCRIPTION
**Pull request by ronhippler**
converted to use webapi.vvo-online.de,
handle error

- [x] closes #21
- [x] closes #22 
- [x] closes #34 
- [x] closes #38 
- [x] closes #20
- [x] closes #40
- [x] closes #41

### CODE REVIEW

**Comment by ronhippler** [comment]
there are some changes:

```js
{
        origin: {
            stop: 'Helmholtzstraße',
            city: 'Dresden',
            coords: [51.0255443264448, 13.725468471273134]
        },
        destination: {
            stop: 'Postplatz',
            city: 'Dresden',
            coords: [51.05055059050917, 13.73357173082639]
        },
        trips: [{
            departure: {
                stop: 'Helmholtzstraße',
                city: 'Dresden',
                platform: {name: 2, type: 'Platform'},
                time: '2017-03-17T14:55:00.000Z',
                coords: [51.0255443264448, 13.725468471273134]
            },
            arrival: {
                stop: 'Postplatz',
                city: 'Dresden',
                platform: {name: 1, type: 'Platform'},
                time: '2017-03-17T15:20:00.000Z',
                coords: [51.05055059050917, 13.73357173082639]
            },
            duration: 25,
            interchanges: 2,
            nodes: [{
                mode: 'Bus',
                line: '85',
                direction: ' Löbtau Süd',
                diva: {number: 21085, network: 'voe'},
                duration: 2,
                stops: [{
                    stop: 'Helmholtzstraße',
                    city: 'Dresden',
                    type: 'Stop',
                    platform: [Object],
                    coords: [Object],
                    arrival: '2017-03-17T14:55:00.000Z',
                    departure: '2017-03-17T14:55:00.000Z'
                },
                    {
                        stop: 'Regensburger Straße',
                        city: 'Dresden',
                        type: 'Stop',
                        platform: [Object],
                        coords: [Object],
                        arrival: '2017-03-17T14:56:00.000Z',
                        departure: '2017-03-17T14:56:00.000Z'
                    },
                    {
                        stop: 'Plauen Nöthnitzer Straße',
                        city: 'Dresden',
                        type: 'Stop',
                        platform: [Object],
                        coords: [Object],
                        arrival: '2017-03-17T14:57:00.000Z',
                        departure: '2017-03-17T14:57:00.000Z'
                    }],
                departure: {
                    stop: 'Helmholtzstraße',
                    city: 'Dresden',
                    platform: {name: 2, type: 'Platform'},
                    time: '2017-03-17T14:55:00.000Z',
                    coords: [51.0255443264448, 13.725468471273134]
                },
                arrival: {
                    stop: 'Plauen Nöthnitzer Straße',
                    city: 'Dresden',
                    platform: {name: 2, type: 'Platform'},
                    time: '2017-03-17T14:57:00.000Z',
                    coords: [51.02707818090382, 13.716544704461048]
                },
                path: [[51.0255353416574, 13.725468137614868],
                    ...]
            },
                {
                    mode: 'Footpath',
                    line: '',
                    direction: '',
                    diva: undefined,
                    duration: 2,
                    stops: undefined,
                    departure: undefined,
                    arrival: undefined,
                    path: [[51.02707818090382, 13.716544704461048],
                        ...]
                },
                {
                    mode: 'Tram',
                    line: '3',
                    direction: ' Wilder Mann',
                    diva: {number: 11003, network: 'voe'},
                    duration: 6,
                    stops: [{
                        stop: 'Plauen Nöthnitzer Straße',
                        city: 'Dresden',
                        type: 'Stop',
                        platform: [Object],
                        coords: [Object],
                        arrival: '2017-03-17T15:06:00.000Z',
                        departure: '2017-03-17T15:06:00.000Z'
                    },
                        {
                            stop: 'Münchner Platz',
                            city: 'Dresden',
                            type: 'Stop',
                            platform: [Object],
                            coords: [Object],
                            arrival: '2017-03-17T15:07:00.000Z',
                            departure: '2017-03-17T15:07:00.000Z'
                        },
                        {
                            stop: 'Nürnberger Platz',
                            city: 'Dresden',
                            type: 'Stop',
                            platform: [Object],
                            coords: [Object],
                            arrival: '2017-03-17T15:08:00.000Z',
                            departure: '2017-03-17T15:08:00.000Z'
                        },
                        {
                            stop: 'Reichenbachstraße',
                            city: 'Dresden',
                            type: 'Stop',
                            platform: [Object],
                            coords: [Object],
                            arrival: '2017-03-17T15:09:00.000Z',
                            departure: '2017-03-17T15:09:00.000Z'
                        },
                        {
                            stop: 'Hauptbahnhof',
                            city: 'Dresden',
                            type: 'Stop',
                            platform: [Object],
                            coords: [Object],
                            arrival: '2017-03-17T15:11:00.000Z',
                            departure: '2017-03-17T15:11:00.000Z'
                        },
                        {
                            stop: 'Hauptbahnhof Nord',
                            city: 'Dresden',
                            type: 'Stop',
                            platform: [Object],
                            coords: [Object],
                            arrival: '2017-03-17T15:12:00.000Z',
                            departure: '2017-03-17T15:12:00.000Z'
                        }],
                    departure: {
                        stop: 'Plauen Nöthnitzer Straße',
                        city: 'Dresden',
                        platform: {name: 1, type: 'Platform'},
                        time: '2017-03-17T15:06:00.000Z',
                        coords: [51.02795994992541, 13.716491750576427]
                    },
                    arrival: {
                        stop: 'Hauptbahnhof Nord',
                        city: 'Dresden',
                        platform: {name: 1, type: 'Platform'},
                        time: '2017-03-17T15:12:00.000Z',
                        coords: [51.041482983761625, 13.735186760804556]
                    },
                    path: [[51.02796914408518, 13.716477834868066],
                       ...]
                },
                {
                    mode: 'Tram',
                    line: '9',
                    direction: ' Kaditz',
                    diva: {number: 11009, network: 'voe'},
                    duration: 5,
                    stops: [{
                        stop: 'Hauptbahnhof Nord',
                        city: 'Dresden',
                        type: 'Stop',
                        platform: [Object],
                        coords: [Object],
                        arrival: '2017-03-17T15:15:00.000Z',
                        departure: '2017-03-17T15:15:00.000Z'
                    },
                        {
                            stop: 'Walpurgisstraße',
                            city: 'Dresden',
                            type: 'Stop',
                            platform: [Object],
                            coords: [Object],
                            arrival: '2017-03-17T15:16:00.000Z',
                            departure: '2017-03-17T15:16:00.000Z'
                        },
                        {
                            stop: 'Prager Straße',
                            city: 'Dresden',
                            type: 'Stop',
                            platform: [Object],
                            coords: [Object],
                            arrival: '2017-03-17T15:18:00.000Z',
                            departure: '2017-03-17T15:18:00.000Z'
                        },
                        {
                            stop: 'Postplatz',
                            city: 'Dresden',
                            type: 'Stop',
                            platform: [Object],
                            coords: [Object],
                            arrival: '2017-03-17T15:20:00.000Z',
                            departure: '2017-03-17T15:20:00.000Z'
                        }],
                    departure: {
                        stop: 'Hauptbahnhof Nord',
                        city: 'Dresden',
                        platform: {name: 1, type: 'Platform'},
                        time: '2017-03-17T15:15:00.000Z',
                        coords: [51.041482983761625, 13.735186760804556]
                    },
                    arrival: {
                        stop: 'Postplatz',
                        city: 'Dresden',
                        platform: {name: 1, type: 'Platform'},
                        time: '2017-03-17T15:20:00.000Z',
                        coords: [51.05055059050917, 13.73357173082639]
                    },
                    path: [[51.041492180131286, 13.73517284486511],
                        ...]
                }]
        },
        ...
        ]
    };
```

any wishes for improvement?

**Comment by ronhippler** [comment]
```js
{ origin: 
   { stop: 'Helmholtzstraße',
     city: 'Dresden',
     coords: [ 51.0255443264448, 13.725468471273134 ] },
  destination: 
   { stop: 'Postplatz',
     city: 'Dresden',
     coords: [ 51.05055059050917, 13.73357173082639 ] },
  trips: 
   [ { departure: 
        { stop: 'Helmholtzstraße',
          city: 'Dresden',
          platform: { name: '1', type: 'Platform' },
          time: 2017-03-18T07:32:00.000Z,
          coords: [ 51.0255443264448, 13.725468471273134 ] },
       arrival: 
        { stop: 'Postplatz',
          city: 'Dresden',
          platform: { name: '1', type: 'Platform' },
          time: 2017-03-18T07:58:00.000Z,
          coords: [ 51.05055059050917, 13.73357173082639 ] },
       duration: 26,
       interchanges: 1,
       nodes: 
        [ { mode: 
             { title: 'Bus',
               name: 'Bus',
               icon_url: 'https://www.dvb.de/assets/img/trans-icon/transport-bus.svg' },
            line: '85',
            direction: ' Striesen',
            diva: { number: 21085, network: 'voe' },
            duration: 5,
            stops: 
             [ { stop: 'Helmholtzstraße',
                 city: 'Dresden',
                 type: 'Stop',
                 platform: [Object],
                 coords: [Object],
                 arrival: 2017-03-18T07:32:00.000Z,
                 departure: 2017-03-18T07:32:00.000Z },
               { stop: 'Stadtgutstraße',
                 city: 'Dresden',
                 type: 'Stop',
                 platform: [Object],
                 coords: [Object],
                 arrival: 2017-03-18T07:34:00.000Z,
                 departure: 2017-03-18T07:34:00.000Z },
               { stop: 'Räcknitzhöhe',
                 city: 'Dresden',
                 type: 'Stop',
                 platform: [Object],
                 coords: [Object],
                 arrival: 2017-03-18T07:35:00.000Z,
                 departure: 2017-03-18T07:35:00.000Z },
               ... 1 more item ],
            departure: 
             { stop: 'Helmholtzstraße',
               city: 'Dresden',
               platform: { name: '1', type: 'Platform' },
               time: 2017-03-18T07:32:00.000Z,
               coords: [ 51.0255443264448, 13.725468471273134 ] },
            arrival: 
             { stop: 'Zellescher Weg',
               city: 'Dresden',
               platform: { name: '1', type: 'Platform' },
               time: 2017-03-18T07:37:00.000Z,
               coords: [ 51.02832041479808, 13.746156560504263 ] },
            path: 
             [ [ 51.0255353416574, 13.725468137614868 ],
               [ 51.02548641939806, 13.725737159122861 ],
               [ 51.025347580931665, 13.726615787933762 ],
               ... 27 more items ] },
          { mode: 
             { title: 'Fussweg',
               name: 'Footpath',
               icon_url: 'https://m.dvb.de/img/walk.svg' },
            line: '',
            direction: '',
            diva: undefined,
            duration: 2,
            stops: undefined,
            departure: undefined,
            arrival: undefined,
            path: 
             [ [ 51.02832041479808, 13.746156560504263 ],
               [ 51.02815545483111, 13.745765462052999 ] ] },
          { mode: 
             { title: 'Straßenbahn',
               name: 'Tram',
               icon_url: 'https://www.dvb.de/assets/img/trans-icon/transport-tram.svg' },
            line: '11',
            direction: ' Bühlau',
            diva: { number: 11011, network: 'voe' },
            duration: 12,
            stops: 
             [ { stop: 'Zellescher Weg',
                 city: 'Dresden',
                 type: 'Stop',
                 platform: [Object],
                 coords: [Object],
                 arrival: 2017-03-18T07:46:00.000Z,
                 departure: 2017-03-18T07:46:00.000Z },
               { stop: 'Strehlener Platz',
                 city: 'Dresden',
                 type: 'Stop',
                 platform: [Object],
                 coords: [Object],
                 arrival: 2017-03-18T07:48:00.000Z,
                 departure: 2017-03-18T07:48:00.000Z },
               { stop: 'Lennéplatz',
                 city: 'Dresden',
                 type: 'Stop',
                 platform: [Object],
                 coords: [Object],
                 arrival: 2017-03-18T07:49:00.000Z,
                 departure: 2017-03-18T07:49:00.000Z },
               ... 6 more items ],
            departure: 
             { stop: 'Zellescher Weg',
               city: 'Dresden',
               platform: { name: '1', type: 'Platform' },
               time: 2017-03-18T07:46:00.000Z,
               coords: [ 51.02815545483111, 13.745765462052999 ] },
            arrival: 
             { stop: 'Postplatz',
               city: 'Dresden',
               platform: { name: '1', type: 'Platform' },
               time: 2017-03-18T07:58:00.000Z,
               coords: [ 51.05055059050917, 13.73357173082639 ] },
            path: 
             [ [ 51.02815545483111, 13.745765462052999 ],
               [ 51.02838777921612, 13.74585972546861 ],
               [ 51.02853945426672, 13.745936703348258 ],
               ... 117 more items ] } ] },
     ... 3 more items ] }
```

**Comment by artifactdev** [comment]
Seems like the following doesn't give a result:

`dvb.route('pragerstrasse', 'postplatz', new Date(), dvb.route.DEPARTURE, function (err, data) {
                console.log(JSON.stringify(data, null, 4));
            });`

data is always null.

**Comment by kiliankoe** [comment]
Haven't tried it yet, but the WebAPI no longer handles stop names directly for anything outside of find requests. See if using the stop's IDs works for you. Prager Straße: `"33000003"`, Postplatz: `"33000037"`.

It would be a nice addition to supply helper functions here, but they probably won't get around sending of multiple requests for that.

**Comment by ronhippler** [comment]
Thats right. The new api uses ids instead of stop names. So you could route from/to POIS and addresses as well.

**Comment by ronhippler** [comment]
I'm going to remove the workaround for .monitor() too. After that every request with find* is used to get the id for something and the other requests will only use ids

**Comment by hoodie** [comment]
@ronhippler I would like to clone your fork, but I can't find it

**Comment by kiliankoe** [comment]
I'm not sure an actual review here is possible anymore^^ 5/85 tests seem to be failing locally though, mostly regarding ServiceErrors. Going to have a look at that.

**Comment by ronhippler** [comment]
I did not update the mocks. Run test-live to run against the api. 

I would like to get feedback about the new interface and the names.

**Comment by kiliankoe** [comment]
Ah, you're right. Live tests are working fine.

I'm really digging the typescript rewrite! Definitely looks good to me!

**Comment by hoodie** [comment]
its alive 🧟

**Pull request merged**
