### PR TITLE
Merged changes from master and split up library

### PR DESCRIPTION
**Pull request by rebugger**
This commit could be a start for ticket #9
* merged the changes from master back into the develop branch and split all methods up accordingly.
* removed sinon from the dev-dependencies since it isn't used for the unit-tests at the moment

If this is merged to master, I recommend deleting the develop branch and start with a fresh develop-branch as the main branch for this repository.
From there all further development can be based on develop.

### CODE REVIEW

**Comment by rebugger** [comment]
(I hope it is ok that I formatted some of your code according to https://github.com/airbnb/javascript)

**Comment by rebugger** [comment]
After playing around with mockery, i think i found a way to mock the unit-tests again. If I have the time, I'll add it to this pullrequest tomorrow.

**Comment by ronhippler** [comment]
any objections or improvements? i think we  should release this soon since `.route()` is broken on master.

**Comment by rebugger** [comment]
Excellent
I think you are good to go.

**Pull request merged**
